version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:80"